#:schema node_modules/wrangler/config-schema.json
name = "browser-linux1"
main = "worker.js"
compatibility_date = "2026-07-15"

# Serve static files from this local directory
[assets]
directory = "./src"
binding = "ASSETS"
